---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: fancy-supply-chain
spec:
  resources:
  - name: source-provider
    templateRef:
      kind: ClusterSourceTemplate
      name: git-source-template
  - name: image-builder
    templateRef:
      kind: ClusterImageTemplate
      name: kpack-template
    sources: 
    - resource: source-provider
      name: source
  serviceAccountRef:
    name: cartographer-pre-built-sa
    namespace: default
  selector:
    workload-type: from-git

