---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartographer-pre-built-sa
  namespace: default
secrets:
- name: docker-credentials
- name: gcr-registry
imagePullSecrets:
- name: docker-credentials
- name: gcr-registry
